### ISSUE TITLE
Make Carousel Loop

### ISSUE THREAD

**Issue by BStephenBB** [HandshakeAlliance/handshakealliance.org#5]
I think it would be nice if the carousel in `Objective.jsx` would loop back to the first slide when the user tries navigating to the next slide when they are on the last slide and vice-versa with the first slide. Or at least visually disable the back and next button when the user is at the first or last slide. 

I'd be happy to make a PR, but I don't think I have permission.

**Comment by kilpatty** [comment]
Thanks @BStephenBB good idea! I think everyone should have the ability to make a PR, but if not I can double check on that - otherwise we can tackle this tonight

**Comment by BStephenBB** [comment]
Ah, I don't have permission to make a new branch on this repo and then make a PR from that branch (how I usually do it), but I can fork the repo and then make a PR from the forked repo. Just did that, [PR here!](https://github.com/HandshakeAlliance/handshakealliance.org/pull/7)

**Comment by kilpatty** [comment]
Ah I see, I can change that. Thanks again! Fixed by #7
